### ISSUE TITLE
Fix: linux logging timestamp bug

### ISSUE THREAD

**Issue by Keyframe** [h3r2tic/notorious6#1]
logging lib: new feature
linux: thread 'main' panicked at 'Could not determine the UTC offset on this system.

fantastic drama. Fix is dead easy anyways, and I got a fix branch here but no permission to push the branch and open a PR. 

Add a `.with_utc_timestamps()` to simple_logger::..new() before init() and that's about it.

**Comment by h3r2tic** [comment]
Fixed, thanks! :)
