### ISSUE TITLE
sRGB transfer functions misnamed

### ISSUE THREAD

**Issue by kcloudy0717** [h3r2tic/notorious6#2]
Hello, I have a question regarding the transfer function defined for sRGB in shader/inc/srgb.hlsl.

Shouldn't the name of the sRGB transfer function be switched? In this [website](https://chrisbrejon.com/cg-cinematography/chapter-1-color-management/) and in the section Transfer functions (OETF and EOTF), it shows the transfer function graph for sRGB and the OETF function graph shows what the hlsl function float sRGB_EOTF(float a) would plot, https://www.desmos.com/calculator/xd5qp8xzev. So I was wondering if this was a minor mistake made when creating the hlsl file.

I'm quite new to color science so sorry if I was the one who made the mistake!

**Comment by h3r2tic** [comment]
You are absolutely correct. Not sure how I got that the other way around, but thank you for pointing it out! Fixed now 💖😀🙏
